[package]
name = "fabien-et-la-trahison-de-olf"
version = "0.3.7"
authors = ["Morgan Van Amerongen <vanamerongen.morgan@gmail.com>", "WaBtey", "Grassouille la Fripouille", "Sombre Roi René"]
edition = "2021"

[workspace]
resolver = "2"

[dependencies]
bevy = "0.7"
bevy_rapier2d = { version = "0.13", features = ["simd-stable", "debug-render"] }
bevy_tweening = { version = "0.4", features = ["bevy_ui"] }
bevy-web-resizer = "2.0"
serde = "1.0"
ron = "0.7"
strum = "0.24"
strum_macros = "0.24"

[profile.dev.package."*"]
opt-level = 3

[profile.dev]
opt-level = 1
